# Generated by Django 3.2.8 on 2021-10-10 16:13

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='serial_no',
            field=models.CharField(default=secrets.token_hex, max_length=50, unique=True, verbose_name='serial'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150, verbose_name='book title'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
