# Generated by Django 3.2.8 on 2021-10-10 14:28

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='serial_no',
            field=models.CharField(default=secrets.token_hex, max_length=50, verbose_name='serial'),
        ),
    ]
