# Generated by Django 3.2.8 on 2021-10-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211010_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='serial_no',
            field=models.CharField(default='a68aa11a81d21222', max_length=50, unique=True, verbose_name='serial'),
        ),
    ]
